//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banner
    {
        public decimal banner_id { get; set; }
        public Nullable<decimal> articledetail_id { get; set; }
        public string tittle_banner { get; set; }
        public string detall_banner { get; set; }
        public string name_image_banner { get; set; }
        public string start_banner { get; set; }
        public string end_banner { get; set; }
        public string url_banner { get; set; }
        public string type_banner { get; set; }
        public Nullable<bool> is_delete_banner { get; set; }
    
        public virtual articledetail articledetail { get; set; }
    }
}
