//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bestarticle
    {
        public decimal bestarticle_id { get; set; }
        public Nullable<decimal> articledetail_id { get; set; }
    
        public virtual articledetail articledetail { get; set; }
    }
}
