//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class box
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public box()
        {
            this.listproduct = new HashSet<listproduct>();
        }
    
        public decimal box_id { get; set; }
        public Nullable<decimal> bussine_id { get; set; }
        public Nullable<decimal> user_id { get; set; }
        public string name_box { get; set; }
        public string code_box { get; set; }
        public Nullable<bool> is_select_box { get; set; }
        public Nullable<bool> is_delete_box { get; set; }
    
        public virtual bussine bussine { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<listproduct> listproduct { get; set; }
    }
}
