//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public decimal comment_id { get; set; }
        public Nullable<decimal> article_id { get; set; }
        public Nullable<decimal> user_id { get; set; }
        public Nullable<System.DateTime> date_comment { get; set; }
        public string name_comment { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<bool> is_delete_comment { get; set; }
    
        public virtual article article { get; set; }
        public virtual user user { get; set; }
    }
}
