//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class information
    {
        public decimal information_id { get; set; }
        public Nullable<decimal> article_id { get; set; }
        public string name_information { get; set; }
        public string detail_information { get; set; }
        public Nullable<bool> is_delete_information { get; set; }
    
        public virtual article article { get; set; }
    }
}
