//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class listproduct
    {
        public decimal list_product_id { get; set; }
        public Nullable<decimal> box_id { get; set; }
        public Nullable<decimal> article_id { get; set; }
        public Nullable<int> num_product { get; set; }
        public Nullable<bool> is_delete_list_product { get; set; }
    
        public virtual article article { get; set; }
        public virtual box box { get; set; }
    }
}
