//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviewarticle
    {
        public decimal reviewarticle_id { get; set; }
        public Nullable<decimal> bussine_id { get; set; }
        public Nullable<decimal> article_id { get; set; }
        public Nullable<bool> is_delete_reviewarticle { get; set; }
    
        public virtual article article { get; set; }
        public virtual bussine bussine { get; set; }
    }
}
