//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subsection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subsection()
        {
            this.articledetail = new HashSet<articledetail>();
        }
    
        public decimal subsection_id { get; set; }
        public Nullable<decimal> section_id { get; set; }
        public string name_sub_section { get; set; }
        public Nullable<bool> is_delete_sub_section { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articledetail> articledetail { get; set; }
        public virtual section section { get; set; }
    }
}
