//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class descriptionarticle
    {
        public decimal descriptionarticle_id { get; set; }
        public Nullable<decimal> article_id { get; set; }
        public string name_descriptionarticle { get; set; }
    
        public virtual article article { get; set; }
    }
}
