//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockarticle
    {
        public decimal stockarticle_id { get; set; }
        public Nullable<decimal> article_id { get; set; }
        public Nullable<System.DateTime> fecha_start_stockarticle { get; set; }
        public Nullable<System.DateTime> fecha_end_stockarticle { get; set; }
        public Nullable<int> queantity_stockarticle { get; set; }
        public string detail_stockarticle { get; set; }
        public Nullable<int> number_actuali_stockarticle { get; set; }
        public string provider_stockarticle { get; set; }
        public string code_stockarticle { get; set; }
        public Nullable<System.DateTime> date_add_stockarticle { get; set; }
    
        public virtual article article { get; set; }
    }
}
