//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articledetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public articledetail()
        {
            this.banner = new HashSet<banner>();
            this.bestarticle = new HashSet<bestarticle>();
        }
    
        public decimal articledetail_id { get; set; }
        public Nullable<decimal> subsection_id { get; set; }
        public Nullable<decimal> article_id { get; set; }
        public Nullable<bool> is_delete_articledetail { get; set; }
    
        public virtual article article { get; set; }
        public virtual subsection subsection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<banner> banner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bestarticle> bestarticle { get; set; }
    }
}
