//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class storeEntities : DbContext
    {
        public storeEntities()
            : base("name=storeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> article { get; set; }
        public virtual DbSet<articledetail> articledetail { get; set; }
        public virtual DbSet<articlerelational> articlerelational { get; set; }
        public virtual DbSet<banner> banner { get; set; }
        public virtual DbSet<bestarticle> bestarticle { get; set; }
        public virtual DbSet<box> box { get; set; }
        public virtual DbSet<bussine> bussine { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<descriptionarticle> descriptionarticle { get; set; }
        public virtual DbSet<groupproduct> groupproduct { get; set; }
        public virtual DbSet<imagearticle> imagearticle { get; set; }
        public virtual DbSet<information> information { get; set; }
        public virtual DbSet<listproduct> listproduct { get; set; }
        public virtual DbSet<reviewarticle> reviewarticle { get; set; }
        public virtual DbSet<section> section { get; set; }
        public virtual DbSet<stockarticle> stockarticle { get; set; }
        public virtual DbSet<subsection> subsection { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
